services:
  postgres:
    image: postgres:16-alpine
    container_name: naknaa_erp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: naknaa_erp_db
    ports:
      - "5432:5432"
    volumes:
      - naknaa_erp_pgdata:/var/lib/postgresql/data

volumes:
  naknaa_erp_pgdata:
