// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NaknaaErp.Infrastructure.Persistence;

#nullable disable

namespace NaknaaErp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625110000_AddSupabaseUserId")]
    partial class AddSupabaseUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Model state is captured in ApplicationDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
