export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh-token',
    logout: '/auth/logout',
  },
  users: '/users',
  user: (id: string) => `/users/${id}`,
  usersStatistics: '/users/statistics',
  userActivity: (id: string) => `/users/${id}/activity`,
  userResetPassword: (id: string) => `/users/${id}/reset-password`,
  roles: '/roles',
  branches: '/branches',
  branch: (id: string) => `/branches/${id}`,
  categories: '/categories',
  category: (id: string) => `/categories/${id}`,
  products: '/products',
  product: (id: string) => `/products/${id}`,
  productBrands: '/products/brands',
  productVariants: (productId: string) => `/products/${productId}/variants`,
  productVariant: (productId: string, variantId: string) =>
    `/products/${productId}/variants/${variantId}`,
  inventory: '/inventory',
  inventoryLocate: (productId: string) => `/inventory/locate/${productId}`,
  inventorySummary: '/inventory/summary',
  inventoryHistory: '/inventory/history',
  inventoryLowStock: '/inventory/low-stock',
  inventoryStockIn: '/inventory/stock-in',
  inventoryStockOut: '/inventory/stock-out',
  inventoryAdjustment: '/inventory/adjustment',
  customers: '/customers',
  customer: (id: string) => `/customers/${id}`,
  customerOptions: '/customers/options',
  suppliers: '/suppliers',
  supplier: (id: string) => `/suppliers/${id}`,
  supplierOptions: '/suppliers/options',
  purchases: '/purchases',
  purchase: (id: string) => `/purchases/${id}`,
  purchasesDashboard: '/purchases/dashboard',
  purchasesReports: '/purchases/reports',
  purchasesReceive: '/purchases/receive',
  sales: '/sales',
  sale: (id: string) => `/sales/${id}`,
  saleReceipt: (id: string) => `/sales/${id}/receipt`,
  salesSummary: '/sales/summary',
  salesProducts: '/sales/products',
  services: '/services',
  service: (id: string) => `/services/${id}`,
  serviceJobs: '/service-jobs',
  serviceJob: (id: string) => `/service-jobs/${id}`,
  serviceJobReceipt: (id: string) => `/service-jobs/${id}/receipt`,
  servicesDashboard: '/services/dashboard',
  warehouses: '/warehouses',
  warehouse: (id: string) => `/warehouses/${id}`,
  warehousesDashboard: '/warehouses/dashboard',
  warehouseTransfers: '/warehouses/transfers',
  warehouseInventory: (id: string) => `/warehouses/${id}/inventory`,
  inventorySearch: '/inventory/search',
  dashboard: '/dashboard',
  dashboardSummary: '/dashboard/summary',
  reports: {
    dashboard: '/reports/dashboard',
    sales: '/reports/sales',
    inventory: '/reports/inventory',
    purchases: '/reports/purchases',
    warehouses: '/reports/warehouses',
    customers: '/reports/customers',
    suppliers: '/reports/suppliers',
    services: '/reports/services',
    users: '/reports/users',
    profitLoss: '/reports/profit-loss',
  },
  settings: {
    business: '/settings/business',
    receipts: '/settings/receipts',
    security: '/settings/security',
    notifications: '/settings/notifications',
    system: '/settings/system',
    branches: '/settings/branches',
    branch: (id: string) => `/settings/branches/${id}`,
  },
  auditLogs: '/audit-logs',
  auditLog: (id: string) => `/audit-logs/${id}`,
} as const
