import type { Customer, Sale, SaleItem } from '@/features/sales/types'
import { DEFAULT_BRANCH_ID } from '@/features/inventory/constants'

export const SALES_STORAGE_KEY = 'naknaa_sales_v1'
export const SALE_ITEMS_STORAGE_KEY = 'naknaa_sale_items_v1'
export const CUSTOMERS_STORAGE_KEY = 'naknaa_customers_v1'
export const SALES_COUNTER_KEY = 'naknaa_sales_counter_v1'
export const AUDIT_LOGS_STORAGE_KEY = 'naknaa_audit_logs_v1'

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust-001',
    name: 'Kwame Mensah',
    phone: '+233 24 123 4567',
    createdAt: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 'cust-002',
    name: 'Ama Boateng',
    phone: '+233 55 987 6543',
    createdAt: '2026-01-20T14:30:00.000Z',
  },
  {
    id: 'cust-003',
    name: 'SoundWave Events',
    phone: '+233 20 456 7890',
    createdAt: '2026-02-01T09:15:00.000Z',
  },
]

const seedSaleOneDate = '2026-06-20T11:30:00.000Z'
const seedSaleTwoDate = '2026-06-21T15:45:00.000Z'

export const SEED_SALES: Sale[] = [
  {
    id: 'sale-001',
    receiptNumber: 'NAK-2026-000001',
    branchId: DEFAULT_BRANCH_ID,
    branchName: 'NakNaa Main Store',
    customerId: 'cust-002',
    customerName: 'Kwame Asare',
    customerPhone: '+233 24 123 4567',
    cashierId: 'demo-admin',
    cashierName: 'NakNaa Admin',
    paymentMethod: 'cash',
    subtotal: 8898,
    discount: 0,
    totalAmount: 8898,
    saleDate: seedSaleOneDate,
    status: 'completed',
  },
  {
    id: 'sale-002',
    receiptNumber: 'NAK-2026-000002',
    branchId: DEFAULT_BRANCH_ID,
    branchName: 'NakNaa Main Store',
    customerId: null,
    customerName: 'Walk-In Customer',
    customerPhone: '-',
    cashierId: 'demo-admin',
    cashierName: 'NakNaa Admin',
    paymentMethod: 'mobile_money',
    subtotal: 2399,
    discount: 100,
    totalAmount: 2299,
    saleDate: seedSaleTwoDate,
    status: 'completed',
  },
  {
    id: 'sale-003',
    receiptNumber: 'NAK-2026-000003',
    branchId: DEFAULT_BRANCH_ID,
    branchName: 'NakNaa Main Store',
    customerId: 'cust-003',
    customerName: 'Mary Owusu',
    customerPhone: '+233 55 987 6543',
    cashierId: 'demo-admin',
    cashierName: 'NakNaa Admin',
    paymentMethod: 'cash',
    subtotal: 3599,
    discount: 0,
    totalAmount: 3599,
    saleDate: '2026-06-18T10:15:00.000Z',
    status: 'completed',
  },
  {
    id: 'sale-004',
    receiptNumber: 'NAK-2026-000004',
    branchId: DEFAULT_BRANCH_ID,
    branchName: 'NakNaa Main Store',
    customerId: 'cust-005',
    customerName: 'Sarah Adjei',
    customerPhone: '+233 27 654 3210',
    cashierId: 'demo-admin',
    cashierName: 'NakNaa Admin',
    paymentMethod: 'mobile_money',
    subtotal: 4798,
    discount: 200,
    totalAmount: 4598,
    saleDate: '2026-06-19T14:20:00.000Z',
    status: 'completed',
  },
  {
    id: 'sale-005',
    receiptNumber: 'NAK-2026-000005',
    branchId: DEFAULT_BRANCH_ID,
    branchName: 'NakNaa Main Store',
    customerId: 'cust-002',
    customerName: 'Kwame Asare',
    customerPhone: '+233 24 123 4567',
    cashierId: 'demo-admin',
    cashierName: 'NakNaa Admin',
    paymentMethod: 'cash',
    subtotal: 2399,
    discount: 0,
    totalAmount: 2399,
    saleDate: '2026-06-21T09:00:00.000Z',
    status: 'completed',
  },
]

export const SEED_SALE_ITEMS: SaleItem[] = [
  {
    id: 'sale-item-001',
    saleId: 'sale-001',
    productId: 'prod-jbl-srx815',
    productVariantId: 'var-jbl-bass',
    productName: 'JBL SRX815',
    variantName: 'Bass',
    quantity: 1,
    unitPrice: 5499,
    totalPrice: 5499,
  },
  {
    id: 'sale-item-002',
    saleId: 'sale-001',
    productId: 'prod-jbl-srx815',
    productVariantId: 'var-jbl-mid',
    productName: 'JBL SRX815',
    variantName: 'Mid',
    quantity: 1,
    unitPrice: 5299,
    totalPrice: 5299,
  },
  {
    id: 'sale-item-003',
    saleId: 'sale-002',
    productId: 'prod-yamaha-psr',
    productVariantId: 'var-psr-61',
    productName: 'Yamaha PSR',
    variantName: '61 Keys',
    quantity: 1,
    unitPrice: 2399,
    totalPrice: 2399,
  },
  {
    id: 'sale-item-004',
    saleId: 'sale-003',
    productId: 'prod-fender-strat',
    productVariantId: 'var-strat-black',
    productName: 'Fender Stratocaster',
    variantName: 'Black',
    quantity: 1,
    unitPrice: 3599,
    totalPrice: 3599,
  },
  {
    id: 'sale-item-005',
    saleId: 'sale-004',
    productId: 'prod-yamaha-psr',
    productVariantId: 'var-psr-61',
    productName: 'Yamaha PSR',
    variantName: '61 Keys',
    quantity: 2,
    unitPrice: 2399,
    totalPrice: 4798,
  },
  {
    id: 'sale-item-006',
    saleId: 'sale-005',
    productId: 'prod-yamaha-psr',
    productVariantId: 'var-psr-61',
    productName: 'Yamaha PSR',
    variantName: '61 Keys',
    quantity: 1,
    unitPrice: 2399,
    totalPrice: 2399,
  },
]

export const SEED_SALES_COUNTER = 5
